---
#Delete host Rancher
- name: Get all Host from a project
  uri:
    method: GET
    status_code: 200
    user: "{{ rancher_api_key }}"
    password: "{{ rancher_api_secret }}"
    HEADER_Accept: "application/json"
    HEADER_Content-Type: "application/json"
    url: "{{ rancher_master_url }}/v1/projects/{{ rancher_project_id }}/hosts"
  register: hostListJson

- name: Deactive Host
  uri:
    method: POST
    status_code: 202
    user: "{{ rancher_api_key }}"
    password: "{{ rancher_api_secret }}"
    HEADER_Accept: "application/json"
    HEADER_Content-Type: "application/json"
    url: "{{ rancher_master_url }}/v1/projects/{{ rancher_project_id }}/hosts/{{item.id}}/?action=deactivate"
  when: (host_to_delete == "") or (item.hostname ==  host_to_delete)
  with_items: "{{hostListJson.json.data}}"
  ignore_errors: yes

- pause: seconds=15

- name: Remove Host
  uri:
    method: POST
    status_code: 202
    user: "{{ rancher_api_key }}"
    password: "{{ rancher_api_secret }}"
    HEADER_Accept: "application/json"
    HEADER_Content-Type: "application/json"
    url: "{{ rancher_master_url }}/v1/projects/{{ rancher_project_id }}/hosts/{{item.id}}/?action=remove"
  when: (host_to_delete == "") or (item.hostname ==  host_to_delete)
  with_items: "{{hostListJson.json.data}}"
  ignore_errors: yes

- pause: seconds=15

- name: Purge Host
  uri:
    method: POST
    status_code: 202
    user: "{{ rancher_api_key }}"
    password: "{{ rancher_api_secret }}"
    HEADER_Accept: "application/json"
    HEADER_Content-Type: "application/json"
    url: "{{ rancher_master_url }}/v1/projects/{{ rancher_project_id }}/hosts/{{item.id}}/?action=purge"
  when: (host_to_delete == "") or (item.hostname ==  host_to_delete)
  with_items: "{{hostListJson.json.data}}"
  ignore_errors: yes
